apiVersion: image-hardening-factory/v1alpha1
kind: HardenedImage
metadata:
  name: jira-lts
  track: release
  description: Hardened Jira and Jira Service Management Data Center LTS image.
source:
  upstream: https://repo1.dso.mil/dsop/atlassian/jira-data-center/jira-lts.git
  mirrorPath: mirrors/repo1/atlassian/jira-lts
  revision: 3df2bc1801cf6f9dd285f9cfd33203903f38741d
  containerfile: Dockerfile
  hardeningManifest: hardening_manifest.yaml
  overlay: overlays/jira-lts/patches
product:
  name: Jira Data Center LTS
  version: 11.3.11
  vendor: Atlassian
  license: proprietary
build:
  platforms: [linux/amd64]
  network: internal-only
  base:
    kind: catalog
    image: ubi9-minimal
  testProfile: jira
  buildArgs:
    JIRA_VERSION: 11.3.11
    JSM_VERSION: 11.3.11
policy:
  profile: atlassian-rhel9-container
  maximumDatabaseAgeHours: 72
  block:
    knownExploited: true
    critical: true
    fixableHigh: true
    newHigh: true
publication:
  quarantineRepository: ${FACTORY_APPLICATION_QUARANTINE_REPOSITORY}
  releaseRepository: ${FACTORY_RELEASE_REPOSITORY}
  imagePath: atlassian/jira-lts
