from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from factory.catalog import ImageDefinition, descendants, topological_order

STAGES = [
    "validate",
    "prepare",
    "build",
    "analyze",
    "compliance",
    "test",
    "policy",
    "import",
    "attest",
    "promote",
]


def _job(template: str, image: ImageDefinition, needs: list[str] | None = None) -> dict[str, Any]:
    job: dict[str, Any] = {
        "extends": template,
        "variables": {
            "FACTORY_IMAGE": image.name,
            "FACTORY_CATALOG_FILE": image.path.as_posix(),
            "FACTORY_TRACK": image.track,
        },
    }
    if needs:
        job["needs"] = [{"job": need, "artifacts": True} for need in needs]
    return job


def render_pipeline(
    images: dict[str, ImageDefinition], roots: set[str] | None = None
) -> dict[str, Any]:
    roots = set(images) if roots is None else roots
    unknown = roots.difference(images)
    if unknown:
        raise ValueError(f"unknown changed images: {', '.join(sorted(unknown))}")
    selected = descendants(images, roots)
    ordered = topological_order(images, selected)

    document: dict[str, Any] = {
        "include": [{"local": "components/jobs.yml"}],
        "stages": STAGES,
    }
    for name in ordered:
        image = images[name]
        base = image.base_image
        base_import = f"import:{base}" if base in selected else None

        document[f"validate:{name}"] = _job(".factory-validate", image)
        prepare_needs = [f"validate:{name}"]
        if base_import:
            prepare_needs.append(base_import)
        document[f"prepare:{name}"] = _job(".factory-prepare", image, prepare_needs)
        document[f"build:{name}"] = _job(".factory-build", image, [f"prepare:{name}"])
        document[f"sbom:{name}"] = _job(".factory-sbom", image, [f"build:{name}"])
        document[f"scan:{name}"] = _job(".factory-scan", image, [f"build:{name}", f"sbom:{name}"])
        document[f"fcs:{name}"] = _job(".factory-fcs", image, [f"build:{name}"])
        document[f"compliance:{name}"] = _job(
            ".factory-compliance", image, [f"build:{name}", f"sbom:{name}"]
        )
        document[f"test:{name}"] = _job(".factory-test", image, [f"build:{name}"])
        document[f"gate:{name}"] = _job(
            ".factory-gate",
            image,
            [
                f"build:{name}",
                f"sbom:{name}",
                f"scan:{name}",
                f"fcs:{name}",
                f"compliance:{name}",
                f"test:{name}",
            ],
        )
        document[f"remediate:{name}"] = _job(".factory-remediate", image, [f"gate:{name}"])
        document[f"patch-mr:{name}"] = _job(".factory-remediation-mr", image, [f"remediate:{name}"])
        document[f"import:{name}"] = _job(
            ".factory-import",
            image,
            [f"prepare:{name}", f"build:{name}", f"gate:{name}"],
        )
        document[f"attest:{name}"] = _job(
            ".factory-attest",
            image,
            [
                f"import:{name}",
                f"gate:{name}",
                f"sbom:{name}",
                f"fcs:{name}",
                f"compliance:{name}",
                f"test:{name}",
            ],
        )
        document[f"promote:{name}"] = _job(
            ".factory-promote", image, [f"import:{name}", f"attest:{name}"]
        )
    return document


def write_pipeline(document: dict[str, Any], output: str | Path) -> None:
    Path(output).write_text(
        "# Generated by image-hardening-factory. Do not edit.\n"
        + yaml.safe_dump(document, sort_keys=False),
        encoding="utf-8",
    )
