"""Render Pipelines-as-Code PipelineRuns from the image catalog.

Every catalog image gets three thin PipelineRuns that all reference the single
``factory-image-build`` Pipeline: pull request validation, default-branch
publication, and a nightly (incoming webhook) rescan. Repository-wide runs for
checks, releases, intake, and maintenance agents are rendered alongside them so
that one command regenerates the whole ``.tekton/`` trigger surface and a unit
test can fail on drift.

Trust model encoded here (and asserted by tests/unit/test_tekton.py):

* PR runs never bind write, signing, release, or SCM-bot credentials.
* Only default-branch push runs publish to quarantine or open release requests.
* PipelineRun definitions are trusted only from the default branch; the
  Repository CR sets ``settings.pipelinerun_provenance: default_branch``.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from factory.catalog import ImageDefinition, load_catalog

GENERATED_HEADER = (
    "# Generated by `make tekton-render` from catalog/images and factory/tekton.py.\n"
    "# Do not edit by hand: tests/unit/test_tekton.py fails when this file drifts.\n"
)
PAC = "pipelinesascode.tekton.dev"
PART_OF = "image-hardening-factory"

# Paths whose change can alter any image's build, evidence, or gate result.
SHARED_BUILD_PATHS = (
    "scripts/**",
    "factory/**",
    "policies/**",
    ".tekton/pipelines/image-build.yaml",
    ".tekton/tasks/**",
)
# High-risk paths that trigger an automatic agent review on pull requests.
REVIEW_PATHS = (
    ".tekton/**",
    "deploy/**",
    "scripts/**",
    "policies/**",
    "factory/**",
    ".claude/**",
    "agents/**",
    "CODEOWNERS",
)

# Pipeline task -> ServiceAccount. Each ServiceAccount maps to a trust class
# with its own NetworkPolicy (deploy/base/network-policies.yaml).
BUILD_SERVICE_ACCOUNTS = {
    "checkout": "factory-offline",
    "validate": "factory-offline",
    "prepare": "factory-reader",
    "build": "factory-buildkit",
    "sbom": "factory-offline",
    "scan": "factory-offline",
    "assessment": "factory-offline",
    "compliance": "factory-offline",
    "test": "factory-test",
    "gate": "factory-offline",
    "quarantine": "factory-importer",
    "release-request": "factory-agent",
    "triage": "factory-agent",
    "remediation": "factory-agent",
}
RELEASE_SERVICE_ACCOUNTS = {
    "checkout": "factory-offline",
    "resolve": "factory-reader",
    "attest": "factory-signer",
    "promote": "factory-promoter",
    "dependents": "factory-offline",
    "triage": "factory-agent",
}
MAINTENANCE_SERVICE_ACCOUNTS = {
    "checkout": "factory-offline",
    "upstream-context": "factory-intake",
    "evidence-context": "factory-reader",
    "agent": "factory-agent",
}
FIPS_NODE_SELECTOR = {"factory.dev/fips-node": "true"}


class _Dumper(yaml.SafeDumper):
    """Render multi-line strings (CEL expressions) as readable literal blocks."""


def _represent_str(dumper: yaml.SafeDumper, value: str) -> yaml.Node:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_Dumper.add_representer(str, _represent_str)


@dataclass(frozen=True)
class RenderOptions:
    default_branch: str = "main"
    workspace_size: str = "80Gi"
    max_keep_runs: int = 5


def _cel_paths(paths: list[str] | tuple[str, ...]) -> str:
    return " ||\n    ".join(f'"{path}".pathChanged()' for path in paths)


def _repo_root(catalog_dir: Path) -> Path:
    try:
        output = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], cwd=catalog_dir, stderr=subprocess.DEVNULL
        )
        return Path(output.decode().strip()).resolve()
    except (OSError, subprocess.CalledProcessError):
        return catalog_dir.resolve().parents[1]


def image_paths(image: ImageDefinition, repo_root: Path | None = None) -> list[str]:
    data = image.data
    path = image.path.resolve()
    root = repo_root or _repo_root(path.parent)
    paths = [path.relative_to(root).as_posix()]
    overlay = data["source"].get("overlay")
    if overlay:
        paths.append(f"{overlay.rstrip('/')}/**")
    profile = data["build"]["testProfile"]
    paths.append(f"tests/profiles/{profile}/**")
    if profile != "base":
        paths.append("tests/profiles/base/**")
    paths.extend(SHARED_BUILD_PATHS)
    return paths


def _workspaces(options: RenderOptions) -> list[dict[str, Any]]:
    return [
        {
            "name": "shared",
            "volumeClaimTemplate": {
                "spec": {
                    "accessModes": ["ReadWriteOnce"],
                    "resources": {"requests": {"storage": options.workspace_size}},
                }
            },
        },
        {"name": "git-auth", "secret": {"secretName": "{{ git_auth_secret }}"}},
    ]


def _task_run_template() -> dict[str, Any]:
    return {
        "serviceAccountName": "factory-pipeline",
        "podTemplate": {
            "securityContext": {
                "runAsNonRoot": True,
                "runAsUser": 10001,
                "runAsGroup": 10001,
                "fsGroup": 10001,
                "fsGroupChangePolicy": "OnRootMismatch",
            },
            "automountServiceAccountToken": False,
        },
    }


def _task_run_specs(accounts: dict[str, str]) -> list[dict[str, Any]]:
    specs = []
    for task, account in accounts.items():
        spec: dict[str, Any] = {"pipelineTaskName": task, "serviceAccountName": account}
        if task in ("build", "test"):
            # Rootless BuildKit/Podman need a pod user namespace (hostUsers: false)
            # so the run step can create nested namespaces and an unmasked /proc.
            spec["podTemplate"] = {"hostUsers": False}
        if task == "compliance":
            spec["podTemplate"] = {
                "nodeSelector": dict(FIPS_NODE_SELECTOR),
                "tolerations": [
                    {
                        "key": "factory.dev/fips-node",
                        "operator": "Equal",
                        "value": "true",
                        "effect": "NoSchedule",
                    }
                ],
            }
        specs.append(spec)
    return specs


def _pipeline_run(
    name: str,
    annotations: dict[str, str],
    labels: dict[str, str],
    pipeline: str,
    params: list[dict[str, str]],
    accounts: dict[str, str],
    options: RenderOptions,
) -> dict[str, Any]:
    return {
        "apiVersion": "tekton.dev/v1",
        "kind": "PipelineRun",
        "metadata": {
            "name": name,
            "annotations": {f"{PAC}/max-keep-runs": str(options.max_keep_runs), **annotations},
            "labels": {"app.kubernetes.io/part-of": PART_OF, **labels},
        },
        "spec": {
            "pipelineRef": {"name": pipeline},
            "params": params,
            "taskRunTemplate": _task_run_template(),
            "taskRunSpecs": _task_run_specs(accounts),
            "workspaces": _workspaces(options),
            "timeouts": {"pipeline": "3h0m0s", "finally": "30m0s"},
        },
    }


def _param(name: str, value: str) -> dict[str, str]:
    return {"name": name, "value": value}


def _common_params() -> list[dict[str, str]]:
    return [
        _param("repo-url", "{{ repo_url }}"),
        _param("revision", "{{ revision }}"),
        _param("runner-image", "{{ runner_image }}"),
        _param("agent-image", "{{ agent_image }}"),
        _param("git-provider", "{{ git_provider }}"),
        _param("git-auth-secret", "{{ git_auth_secret }}"),
    ]


def image_runs(
    image: ImageDefinition, options: RenderOptions, repo_root: Path | None = None
) -> dict[str, dict[str, Any]]:
    name = image.name
    branch = options.default_branch
    paths = _cel_paths(image_paths(image, repo_root))
    labels = {"factory.dev/image": name}
    runs: dict[str, dict[str, Any]] = {}

    runs[f"{name}-on-pull-request.yaml"] = _pipeline_run(
        f"{name}-on-pull-request",
        {
            f"{PAC}/on-cel-expression": (
                f'event == "pull_request" && target_branch == "{branch}" && (\n    {paths})'
            ),
            f"{PAC}/cancel-in-progress": "true",
        },
        {**labels, "factory.dev/trigger": "pull-request"},
        "factory-image-build",
        [
            _param("image", name),
            *_common_params(),
            _param("event-type", "pull_request"),
            _param("branch", "{{ source_branch }}"),
            _param("change-id", "{{ pull_request_number }}"),
            _param("publish", "false"),
            _param("enable-agents", "{{ enable_agents }}"),
            _param("enable-remediation", "false"),
            _param("enable-release-request", "false"),
        ],
        BUILD_SERVICE_ACCOUNTS,
        options,
    )
    runs[f"{name}-on-push.yaml"] = _pipeline_run(
        f"{name}-on-push",
        {
            f"{PAC}/on-cel-expression": (
                f'event == "push" && target_branch == "{branch}" && (\n    {paths})'
            ),
        },
        {**labels, "factory.dev/trigger": "push"},
        "factory-image-build",
        [
            _param("image", name),
            *_common_params(),
            _param("event-type", "push"),
            _param("branch", branch),
            _param("scm-secret", "factory-scm-bot"),
            _param("publish", "true"),
            _param("enable-agents", "{{ enable_agents }}"),
            _param("enable-remediation", "true"),
            _param("enable-release-request", "true"),
        ],
        BUILD_SERVICE_ACCOUNTS,
        options,
    )
    runs[f"{name}-on-schedule.yaml"] = _pipeline_run(
        f"{name}-on-schedule",
        {
            f"{PAC}/on-event": "[incoming]",
            f"{PAC}/on-target-branch": f"[{branch}]",
        },
        {**labels, "factory.dev/trigger": "schedule"},
        "factory-image-build",
        [
            _param("image", name),
            *_common_params(),
            _param("event-type", "incoming"),
            _param("branch", branch),
            _param("scm-secret", "factory-scm-bot"),
            # Nightly runs re-gate the current pins against fresh vulnerability
            # data. They never publish; a deny hands off to the remediation agent.
            _param("publish", "false"),
            _param("enable-agents", "{{ enable_agents }}"),
            _param("enable-remediation", "true"),
            _param("enable-release-request", "false"),
        ],
        BUILD_SERVICE_ACCOUNTS,
        options,
    )
    if image.base_image:
        runs[f"{name}-on-base-release.yaml"] = _pipeline_run(
            f"{name}-on-base-release",
            {
                f"{PAC}/on-event": "[incoming]",
                f"{PAC}/on-target-branch": f"[{branch}]",
            },
            {**labels, "factory.dev/trigger": "base-release"},
            "factory-image-build",
            [
                _param("image", name),
                *_common_params(),
                _param("event-type", "incoming"),
                _param("branch", branch),
                _param("scm-secret", "factory-scm-bot"),
                # Triggered by the release pipeline after the base was promoted:
                # rebuild on the new base, publish, and request release.
                _param("publish", "true"),
                _param("enable-agents", "{{ enable_agents }}"),
                _param("enable-remediation", "true"),
                _param("enable-release-request", "true"),
            ],
            BUILD_SERVICE_ACCOUNTS,
            options,
        )
    return runs


def repository_runs(options: RenderOptions) -> dict[str, dict[str, Any]]:
    branch = options.default_branch
    runs: dict[str, dict[str, Any]] = {}
    runs["factory-checks-on-pull-request.yaml"] = _pipeline_run(
        "factory-checks-on-pull-request",
        {
            f"{PAC}/on-event": "[pull_request]",
            f"{PAC}/on-target-branch": f"[{branch}]",
            f"{PAC}/cancel-in-progress": "true",
        },
        {"factory.dev/trigger": "pull-request"},
        "factory-checks",
        [
            _param("repo-url", "{{ repo_url }}"),
            _param("revision", "{{ revision }}"),
            _param("runner-image", "{{ runner_image }}"),
        ],
        {"checkout": "factory-offline", "checks": "factory-offline"},
        options,
    )
    runs["release-on-push.yaml"] = _pipeline_run(
        "release-on-push",
        {
            f"{PAC}/on-cel-expression": (
                f'event == "push" && target_branch == "{branch}" && "releases/**".pathChanged()'
            ),
        },
        {"factory.dev/trigger": "release"},
        "factory-image-release",
        [
            _param("repo-url", "{{ repo_url }}"),
            _param("revision", "{{ revision }}"),
            _param("sender", "{{ sender }}"),
            _param("enable-agents", "{{ enable_agents }}"),
            _param("runner-image", "{{ runner_image }}"),
            _param("agent-image", "{{ agent_image }}"),
            _param("git-provider", "{{ git_provider }}"),
            _param("git-auth-secret", "{{ git_auth_secret }}"),
        ],
        RELEASE_SERVICE_ACCOUNTS,
        options,
    )
    runs["intake-on-schedule.yaml"] = _pipeline_run(
        "intake-on-schedule",
        {f"{PAC}/on-event": "[incoming]", f"{PAC}/on-target-branch": f"[{branch}]"},
        {"factory.dev/trigger": "schedule"},
        "factory-intake",
        [
            _param("repo-url", "{{ repo_url }}"),
            _param("revision", "{{ revision }}"),
            _param("runner-image", "{{ runner_image }}"),
            _param("intake-runner-image", "{{ intake_runner_image }}"),
        ],
        {"checkout": "factory-offline", "intake": "factory-intake"},
        options,
    )
    runs["security-data-on-schedule.yaml"] = _pipeline_run(
        "security-data-on-schedule",
        {f"{PAC}/on-event": "[incoming]", f"{PAC}/on-target-branch": f"[{branch}]"},
        {"factory.dev/trigger": "schedule"},
        "factory-security-data",
        [
            _param("repo-url", "{{ repo_url }}"),
            _param("revision", "{{ revision }}"),
            _param("runner-image", "{{ runner_image }}"),
            _param("intake-runner-image", "{{ intake_runner_image }}"),
        ],
        {"checkout": "factory-offline", "security-data": "factory-intake"},
        options,
    )
    for agent in ("upstream-sync", "exception-steward"):
        runs[f"agent-{agent}-on-schedule.yaml"] = _pipeline_run(
            f"agent-{agent}-on-schedule",
            {f"{PAC}/on-event": "[incoming]", f"{PAC}/on-target-branch": f"[{branch}]"},
            {"factory.dev/trigger": "schedule", "factory.dev/agent": agent},
            "factory-agent-maintenance",
            [
                _param("agent", agent),
                _param("enable-agents", "{{ enable_agents }}"),
                _param("mode", "propose-change"),
                *_common_params(),
                _param("intake-runner-image", "{{ intake_runner_image }}"),
                _param("event-type", "incoming"),
                _param("branch", branch),
                _param("scm-secret", "factory-scm-bot"),
            ],
            MAINTENANCE_SERVICE_ACCOUNTS,
            options,
        )
    review_params = [
        _param("agent", "pipeline-reviewer"),
        _param("enable-agents", "{{ enable_agents }}"),
        _param("mode", "report"),
        *_common_params(),
        _param("event-type", "pull_request"),
        _param("branch", "{{ source_branch }}"),
        _param("base-branch", "{{ target_branch }}"),
        _param("change-id", "{{ pull_request_number }}"),
        _param("checkout-depth", "50"),
    ]
    runs["agent-pipeline-review-on-pull-request.yaml"] = _pipeline_run(
        "agent-pipeline-review-on-pull-request",
        {
            f"{PAC}/on-cel-expression": (
                f'event == "pull_request" && target_branch == "{branch}" && (\n    '
                f"{_cel_paths(REVIEW_PATHS)})"
            ),
            f"{PAC}/cancel-in-progress": "true",
        },
        {"factory.dev/trigger": "pull-request", "factory.dev/agent": "pipeline-reviewer"},
        "factory-agent-maintenance",
        review_params,
        MAINTENANCE_SERVICE_ACCOUNTS,
        options,
    )
    runs["agent-pipeline-review-on-comment.yaml"] = _pipeline_run(
        "agent-pipeline-review-on-comment",
        {f"{PAC}/on-comment": "^/review"},
        {"factory.dev/trigger": "comment", "factory.dev/agent": "pipeline-reviewer"},
        "factory-agent-maintenance",
        review_params,
        MAINTENANCE_SERVICE_ACCOUNTS,
        options,
    )
    return runs


def render(catalog_dir: str | Path, options: RenderOptions | None = None) -> dict[str, str]:
    options = options or RenderOptions()
    images = load_catalog(catalog_dir)
    root = _repo_root(Path(catalog_dir))
    documents: dict[str, dict[str, Any]] = {}
    for name in sorted(images):
        documents.update(image_runs(images[name], options, root))
    documents.update(repository_runs(options))
    return {
        filename: GENERATED_HEADER
        + yaml.dump(document, Dumper=_Dumper, sort_keys=False, width=100, default_flow_style=False)
        for filename, document in sorted(documents.items())
    }


def write(rendered: dict[str, str], output: str | Path) -> list[Path]:
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    written = []
    for filename, content in rendered.items():
        path = output / filename
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def drift(rendered: dict[str, str], output: str | Path) -> list[str]:
    """Return generated filenames that are missing, stale, or orphaned."""
    output = Path(output)
    problems = []
    for filename, content in rendered.items():
        path = output / filename
        if not path.exists():
            problems.append(f"missing: {filename}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"stale: {filename}")
    for path in sorted(output.glob("*.yaml")):
        if path.name not in rendered and GENERATED_HEADER in path.read_text(encoding="utf-8"):
            problems.append(f"orphaned: {path.name}")
    return problems
