apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/repo1
    contents:
      - path: bitbucket-lts
        git:
          url: https://repo1.dso.mil/dsop/atlassian/bitbucket-data-center/bitbucket-lts.git
          ref: af750f62df2325dde68ea83ff64974c5a4d9cd75
      - path: confluence-lts
        git:
          url: https://repo1.dso.mil/dsop/atlassian/confluence-data-center/confluence-lts.git
          ref: 9fcf1b3eaf43f47dc06f7f87244644b797b2d608
      - path: jira-lts
        git:
          url: https://repo1.dso.mil/dsop/atlassian/jira-data-center/jira-lts.git
          ref: 3df2bc1801cf6f9dd285f9cfd33203903f38741d
      - path: ubi9-minimal
        git:
          url: https://repo1.dso.mil/dsop/redhat/ubi/9.x/ubi9-minimal.git
          ref: ae0ab69ce2e3b5935ff43fb65456856bab591176
      - path: ubi10-minimal
        git:
          url: https://repo1.dso.mil/dsop/redhat/ubi/10.x/ubi10-minimal.git
          ref: 3cd1849717122c8092a62a789269db71845363dd
